spring:
  profiles:
    active: dev
  config:
    import: classpath:application-secret.yml
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      port: 6379
      host: 172.17.0.1
medium:
  jwt-key: ${custom.jwt-secret-key}



